name: CD Pipeline - Deploy to EC2

on:
  workflow_run:
    workflows: ["CI Pipeline - Build & Test"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
    - name: Deploy to AWS EC2 via SSH
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.HOST_DNS }}
        username: ubuntu   # Jo Amazon Linux EC2 hoy to 'ec2-user' lakho
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          sudo docker stop myapp-container || true
          sudo docker rm myapp-container || true
          sudo docker pull ${{ secrets.DOCKER_USERNAME }}/myapp:latest
          sudo docker run -d -p 80:80 --name myapp-container ${{ secrets.DOCKER_USERNAME }}/myapp:latest
